### ISSUE TITLE
你好，刚刚发现一个乱码的bug

### ISSUE THREAD

**Issue by idashy** [yuanbin3136/zhihu_daily#1]
点开文章，详情页面全是乱码，链接是gif动图
[Bug](http://p16vszsby.bkt.clouddn.com/%E4%B9%B1%E7%A0%81.gif?attname=&e=1524302475&token=NYX5b6QaVFGMB5vzHSgy0lp2jGcBlHXbg7YIca07:wnCYQfLUyAiKGLvpCNMTuVeKNwc)

**Comment by yuanbin3136** [comment]
非常感谢您的反馈，
经过确认，发现[https://github.com/yuanbin3136/zhihu_daily/blob/master/app/src/main/java/com/wind/yuanbin/daily/DetailsActivity.java](url)中加载网页的代码----

> webView.loadData(html,"text/html","utf-8");

在部分机型下会出现乱码，例如 Studio的7.1.1版本模拟器。
已做出如下修改：

> webView.loadData(html,"text/html;charset=UTF-8",null);
